/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        rID.setEnabled(false);
        autonumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rNama = new javax.swing.JTextField();
        rID = new javax.swing.JTextField();
        rUmur = new javax.swing.JTextField();
        rNomorKTP = new javax.swing.JTextField();
        rNomorSIM = new javax.swing.JTextField();
        rUsername = new javax.swing.JTextField();
        rPassword = new javax.swing.JPasswordField();
        rKonPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("REGISTER");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 30, 110, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 110, 149, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 150, 149, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Umur");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 149, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nomor SIM");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 270, 149, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nomor KTP");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 230, 149, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 350, 149, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Username");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 310, 149, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Konfirmasi Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 390, 160, 17);

        rNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNamaActionPerformed(evt);
            }
        });
        getContentPane().add(rNama);
        rNama.setBounds(230, 140, 200, 30);

        rID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rIDActionPerformed(evt);
            }
        });
        getContentPane().add(rID);
        rID.setBounds(230, 100, 200, 30);

        rUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUmurActionPerformed(evt);
            }
        });
        getContentPane().add(rUmur);
        rUmur.setBounds(230, 180, 200, 30);

        rNomorKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNomorKTPActionPerformed(evt);
            }
        });
        getContentPane().add(rNomorKTP);
        rNomorKTP.setBounds(230, 220, 200, 30);

        rNomorSIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNomorSIMActionPerformed(evt);
            }
        });
        getContentPane().add(rNomorSIM);
        rNomorSIM.setBounds(230, 260, 200, 30);

        rUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(rUsername);
        rUsername.setBounds(230, 300, 200, 30);
        getContentPane().add(rPassword);
        rPassword.setBounds(230, 340, 200, 30);
        getContentPane().add(rKonPassword);
        rKonPassword.setBounds(230, 380, 200, 30);

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(60, 450, 101, 43);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal);
        btnBatal.setBounds(310, 450, 101, 43);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Screenshot_20230112_211600.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-10, -10, 590, 530);

        setSize(new java.awt.Dimension(503, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNamaActionPerformed

    private void rIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rIDActionPerformed

    private void rUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rUmurActionPerformed

    private void rNomorKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNomorKTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNomorKTPActionPerformed

    private void rNomorSIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNomorSIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNomorSIMActionPerformed

    private void rUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rUsernameActionPerformed

    private boolean checkPass(String password){
        if(password.length() < 4){
            JOptionPane.showMessageDialog(null, "Password harus minimal 4 karakter");
            return false;
        }
        
        int counter1 = 0, counter2 = 0;
        for(int i = 0; i < password.length(); i++){
            if(Character.isLetter(password.charAt(i))){
                counter1++;
            }
            
            if(Character.isDigit(password.charAt(i))){
                counter2++;
            }  
        }
//        System.out.println(counter1 + " " + counter2);
        if(counter1 < 1 || counter2 < 1){
            JOptionPane.showMessageDialog(null, "Password harus memiliki setidaknya 1 huruf dan angka");
            return false;
        }
        return true;
    }
    
    private boolean nama1Check(String nama){
        if(nama.length() < 5){
            JOptionPane.showMessageDialog(null, "Nama setidaknya harus 5 karakter");
            return false;
        }
        int counter = 0;
        for(int i = 0; i < nama.length(); i++){
            if(Character.isLetter(nama.charAt(i))){
                counter++;
            }else{
              JOptionPane.showMessageDialog(null, "Nama harus huruf");
              return false;
            }
        }
        if(counter == nama.length()){
            return true;
        }else{
            return false;
        }
    }
    
    private boolean namaCheck(String nama){
        if(nama.length() > 3){
            JOptionPane.showMessageDialog(null, "Umurmu tidak masuk akal");
            return false;
        }
        int counter = 0;
        for(int i = 0; i < nama.length(); i++){
            if(!Character.isDigit(nama.charAt(i))){
              JOptionPane.showMessageDialog(null, "Umur harus Digit");
              return false;
            }
        }
        return true;
    }
    
    private boolean ktpCheck(String nama){
        int counter = 0;
        for(int i = 0; i < nama.length(); i++){
            if(!Character.isDigit(nama.charAt(i))){
              JOptionPane.showMessageDialog(null, "KTP harus Digit");
              return false;
            }
        }
        return true;
    }
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String id = rID.getText().toString().trim();
        String username = rUsername.getText().toString().trim();
        String password = rPassword.getText().toString().trim();
        String nama = rNama.getText().toString().trim();
        String umur = rUmur.getText().toString().trim();
        String nKTP = rNomorKTP.getText().toString().trim();
        String nSIM = rNomorSIM.getText().toString().trim();
        String konPassword = rKonPassword.getText().toString().trim();
        
        if(!password.equals(konPassword)){
            JOptionPane.showMessageDialog(null, "Password tidak cocok");
        }else if(password.isEmpty() || username.isEmpty()){
            JOptionPane.showMessageDialog(null, "Username atau Password tidak bisa kosong");
        }else if(umur.isEmpty()){
            JOptionPane.showMessageDialog(null, "Umur tidak bisa kosong");
        }else if(!namaCheck(umur)){
        }else if(nama.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama tidak bisa kosong");
        }else if(!nama1Check(nama)){
        }else if(nKTP.length() != 16){
            JOptionPane.showMessageDialog(null, "Panjang no KTP harus sama dengan 16");
        }else if(!ktpCheck(nKTP)){
        }else if(!checkPass(password)){
        }else{
            String query = "INSERT INTO `data_user`(`ID`, `Username`, `Password`, `Nama`, `Umur`, `Nomor KTP`, `Ketersediaan Supir`, `Nomor SIM`, `Durasi`, `ID_Supir`, `Plat_Mobil`)"
                + "VALUES ('" + id +"','" + username +"','" + password +"','" + nama +"','" + umur +"','" + nKTP +"','','" + nSIM +"','0','0','-')";
            Koneksi con = new Koneksi();
            con.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Akun sukses dibuat");
            this.dispose();
            Login a = new Login();
            a.setVisible(true);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    
    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:\
        this.dispose();
        Login a = new Login();
        a.setVisible(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField rID;
    private javax.swing.JPasswordField rKonPassword;
    private javax.swing.JTextField rNama;
    private javax.swing.JTextField rNomorKTP;
    private javax.swing.JTextField rNomorSIM;
    private javax.swing.JPasswordField rPassword;
    private javax.swing.JTextField rUmur;
    private javax.swing.JTextField rUsername;
    // End of variables declaration//GEN-END:variables

    private void autonumber() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String query = "SELECT * FROM `data_user` ORDER BY ID DESC";
        Koneksi con = new Koneksi();
        ResultSet rs = con.execQuery(query);
        try {
            if(rs.next()){
                String NoID = rs.getString("ID");
                String ID = "" + (Integer.parseInt(NoID)+1);
                rID.setText(ID);
            }else{
                String NoID = rs.getString("ID");
                String ID = "" + (Integer.parseInt("1")+1);
                rID.setText(ID);
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
